version: '3.8'

services:
  web:
    build: ./webapp
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./webapp/:/usr/src/webapp/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_user
      - POSTGRES_DB=django_dev

volumes:
  postgres_data:
